import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import FooterStandard from "@/components/mvpblocks/footer-standard";
import CardNav from "@/components/CardNav";
import { navItems } from "@/constants/constant";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <CardNav
          logo="/navImages/logo.jpg"
          logoAlt="UrbanSlay"
          items={navItems}
          baseColor="#fff"
          menuColor="#000"
          buttonBgColor="#111"
          buttonTextColor="#fff"
          ease="power3.out"
          theme="color"
        />
        {children}
        <FooterStandard />
      </body>
    </html>
  );
}
