import { Geist, Geist_Mono, Cormorant_Garamond } from "next/font/google";
import "./globals.css";
import FooterStandard from "@/components/mvpblocks/footer-standard";
import CardNav from "@/components/CardNav";
import { ClerkProvider } from "@clerk/nextjs";
import { navItems } from "@/constants/constant";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

const cormorant = Cormorant_Garamond({
  variable: "--font-cormorant",
  subsets: ["latin"],
  weight: ["300", "400", "500", "600", "700"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

import Badge from "@/components/Badge";
import { ShopProvider } from "@/context/ShopContext";
import FloatingContact from "@/components/FloatingContact";

const badgeMessages = [
  { text: "Free Delivery on orders over ₹600", linkText: "Learn more" },
  { text: "Cash on Delivery currently available ✨", linkText: "Learn more" },
];

export default function RootLayout({ children }) {
  return (
    <ClerkProvider>

      <html lang="en">
        <body
          className={`${geistSans.variable} ${geistMono.variable} ${cormorant.variable} antialiased`}
        >
          <ShopProvider>
            <div className=" top-0 left-0 right-0 z-100">
              <Badge messages={badgeMessages} />
            </div>
            <CardNav
              logo="/navImages/logo.jpg"
              logoAlt="UrbanSlay"
              items={navItems}
              baseColor="#fff"
              menuColor="#000"
              buttonBgColor="#111"
              buttonTextColor="#fff"
              ease="power3.out"
              theme="color"
              className="top-[3.5em]! md:top-[3em]!"
            />
            <div className="pt-10 md:pt-12">
              {children}
            </div>
            <FloatingContact />
            <FooterStandard />
          </ShopProvider>
        </body>
      </html>
    </ClerkProvider>
  );
}

